### ISSUE TITLE
Deployment failed on Ubuntu 20.04

### ISSUE THREAD

**Issue by Fred2VOX** [systemli/ansible-role-spamassassin#8]
Hi,

In first, thanks to make this role.

I'm trying apply this role on Ubuntu 20.04 and got the following result:

`
failed: [127.0.0.1] (item=razor-admin -home=/etc/spamassassin/.razor -create) => {"ansible_loop_var": "item", "changed": true, "cmd": ["razor-admin", "-home=/etc/spamassassin/.razor", "-create"], "delta": "0:00:21.163660", "end": "2020-11-08 13:16:29.464357", "item": "razor-admin -home=/etc/spamassassin/.razor -create", "msg": "non-zero return code", "rc": 2, "start": "2020-11-08 13:16:08.300697", "stderr": "Use of uninitialized value in concatenation (.) or string at /usr/share/perl5/Razor2/Client/Config.pm line 33.\nUse of uninitialized value in concatenation (.) or string at /usr/share/perl5/Razor2/Client/Config.pm line 122.\nnextserver: Bootstrap discovery failed. Giving up.", "stderr_lines": ["Use of uninitialized value in concatenation (.) or string at /usr/share/perl5/Razor2/Client/Config.pm line 33.", "Use of uninitialized value in concatenation (.) or string at /usr/share/perl5/Razor2/Client/Config.pm line 122.", "nextserver: Bootstrap discovery failed. Giving up."], "stdout": "", "stdout_lines": []}
`

How can I fix it, please? If I want to keep Razor.

Fred

**Comment by t2d** [comment]
Hey, thank you for your kind words. I added testing for Ubuntu 20.04 in branch `ubuntu2004` and can confirm that it doesn't work right now out of the box.
https://github.com/systemli/ansible-role-spamassassin/runs/1380860198?check_suite_focus=true

We don't use this OS and can't therefore not fix your problem, but any PR is welcome
